### PR TITLE
Fixing schema validation error 

### LINKED ISSUE #11: Schema validation error
Hey guys, when I try to use this plugin I receive this error from serverless:
```
  Serverless Error ----------------------------------------

  Configuration error:
       at 'functions.graphql.events[0].http.authorizer': unrecognized property 'localAuthorizer'
       at 'functions.graphql.events[1].http.authorizer': unrecognized property 'localAuthorizer'
```
I made some searching and it may be related to forced schema validation added in 2.7.0:
https://www.serverless.com/framework/docs/providers/aws/guide/plugins/#extending-validation-schema

### PR DESCRIPTION
**Pull request by dimabory**
According to https://www.serverless.com/framework/docs/guides/plugins/custom-configuration#validating-the-configuration
Fixes #11

### CODE REVIEW

**Comment by turakvlad** [comment]
Could we please merge this? I would like to get rid of this error as well.

**Comment by nlang** [comment]
@turakvlad here you go. Thanks a bunch @dimabory for fixing this issue 🙏

**Comment by turakvlad** [comment]
Hey @nlang 

Thank you for such a quick reply. I just wanted to ask whether this code was built properly and pushed as v1.0.4 to NPM – https://www.npmjs.com/package/serverless-offline-local-authorizers-plugin.

I upgraded the package to the latest version and still have this issue. I cannot see this code added by @dimabory in `AwsLocalAuthorizersPlugin.js`:

Screenshot 2022-02-09 at 15 02 34 

Thank you!

**Comment by nlang** [comment]
@turakvlad thanks for pointing that out. Should now be fixed with 1.1.1

**Comment by turakvlad** [comment]
Hey @nlang 

I am afraid that either 1.1.0, and 1.1.1, and 1.1.2 stopped working for me with Serverless 3 but 1.0.4 works well.

Screenshot 2022-02-11 at 13 34 24

I am not sure which exact PR has caused this issue. Anyway, just wanted to let you know. I am not sure whether the plugin works with Serverless 2 but I can assume that it does not. 

Thanks for your help.

**Comment by nlang** [comment]
@turakvlad the provided example project works for me with serverless 2.72.2
image

I can confirm that the error you're experiencing is thrown with serverless v3

**Comment by turakvlad** [comment]
@nlang 

Does at least one of the functions in your `serverless.yml` use the plugin? I downgraded the Serverless to V2 and it works for me but I can still see the configuration error.

**Comment by nlang** [comment]
@turakvlad
Yes, see the examples/simple folder.
Did you move the config from `events.?.http.authorizer.localAuthorizer` to `events.?.http.localAuthorizer`?

image

**Comment by turakvlad** [comment]
@nlang 

Ups, sorry, you are right. I did not move the plugin's config to `http`. I did it and I still have an issue above with Serverless V3. I looked through the code and it seems that Serverless V3 uses newer AJV validator that has some breaking changes comparing to the one in Serverless V2.

In this PR we've merged:

```
        this.serverless.configSchemaHandler.defineFunctionEventProperties('aws', 'http', {
            type: 'object',
            properties: {
                localAuthorizer: {
                    properties: {
                        name: { type: 'string' },
                        type: {
                            anyOf: ['token', 'cognito_user_pools', 'request', 'aws_iam'].map(v => ({ type: 'string', regexp: new RegExp(`^${v}$`, 'i').toString() })),
                        },
                    }
                },
            },
        });
```

The missing part is `type: 'object'` in `localAuthorizer` object. So, it should be like:

```
        this.serverless.configSchemaHandler.defineFunctionEventProperties('aws', 'http', {
            type: 'object',
            properties: {
                localAuthorizer: {
                    type: 'object', // THIS IS NEEDED TO SUPPORT V3.
                    properties: {
                        name: { type: 'string' },
                        type: {
                            anyOf: ['token', 'cognito_user_pools', 'request', 'aws_iam'].map(v => ({ type: 'string', regexp: new RegExp(`^${v}$`, 'i').toString() })),
                        },
                    }
                },
            },
        });
```

I just opened a PR – https://github.com/nlang/serverless-offline-local-authorizers-plugin/pull/20. You can check it and merge it everything looks fine. It would be great if you could merge it and publish one more version on NPM :) 

I tested the plugin with Serverless V2 and Serverless V3. Both versions worked well. 

Thanks and have a great day!

**Comment by nlang** [comment]
@turakvlad already fixed it myself. Thanks anyways. v1.2.0 is published with v3 compatibility.

**Comment by turakvlad** [comment]
@nlang , thank you very much!

The latest version is still v1.1.2 on NPM – https://www.npmjs.com/package/serverless-offline-local-authorizers-plugin. You haven't published it on NPM yet?

**Comment by nlang** [comment]
@turakvlad yeah that took some time to show up...now it's visible at least for me

**Pull request merged**
